---
title: "LinearModel_Nick"
author: "Nicholas Mobley"
date: "12/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(gridExtra)
library(ggthemes)
library(reportr)
library(knitr)
library(splines)
```


```{r}
setwd("C:/Users/nmobl/Desktop/School/Fall2019/Stat-S431/S431Project")
kki.demo <- read.csv("Data\\KKI_demographicInfo.csv")
kki.hand <-  read.csv("C:\\Users\\nmobl\\Desktop\\School\\Fall2019\\STAT-S431\\S431Project\\Data\\KKI_handedness.csv")
kki.social <- read.csv("Data\\KKI_SocialResponsivenessScaleQuestionnaire.csv")
kki.movement <- read.csv("Data\\KKI_movementAssessmentBatteryforChildren.csv")
#Fix odd ID col
colnames(kki.hand)[1] <- "ID"
colnames(kki.demo)[1] <- "ID"
colnames(kki.social)[1] <- "ID"
colnames(kki.movement)[1] <- "ID"
kki <- merge(kki.demo,kki.social)
kki <- merge(kki,kki.movement)
kki <- merge(kki,kki.hand)
#Now have all the data in a huge data frame
#Removing N/A values. Mostly removing second visits.
kki <- na.omit(kki)
kki <- subset(kki,kki$mABC_AGE<14)
kki2 <- filter(kki,PrimaryDiagnosis != "None",SecondaryDiagnosis ==c("Yes", "No"))
multdia <- filter(kki, PrimaryDiagnosis != "None", SecondaryDiagnosis =="Yes")
singdia <- filter(kki, PrimaryDiagnosis != "None" , SecondaryDiagnosis == "No")
nodia <- filter(kki, PrimaryDiagnosis =="None" , SecondaryDiagnosis =="No")
```

```{r}
kki.adhd <- subset(kki,kki$PrimaryDiagnosis == "ADHD")
kki.adhd1 <- subset(kki.adhd,kki.adhd$SRS_VERSION == 1)
kki.adhd2 <- subset(kki.adhd,kki.adhd$SRS_VERSION == 2)
```

```{r}
ggplot(data = kki.adhd,aes(group = SRS_VERSION, y = SRS_TotalRawScore,colour = SRS_VERSION)) + facet_wrap(~ADHD_Subtype) + geom_boxplot()
```

```{r}
lm.basic <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore,data = kki.adhd)
``` 

```{r}
summary(lm.basic)
```

```{r}
fit <- lm(SRS_TotalRawScore ~ mABC_AimingAndCatching.Component.StandardScore + mABC_Balance.Component.StandardScore + EdinburghHandedness_Integer + GAI + ADHD_Subtype + Gender + bs(mABC_AGE,knots = 10), data = kki.adhd1)
summary(fit)
```

```{r}
fit <- lm(SRS_TotalRawScore ~ mABC_AimingAndCatching.Component.StandardScore + mABC_Balance.Component.StandardScore + EdinburghHandedness_Integer + GAI + ADHD_Subtype + Gender + mABC_AGE, data = kki.adhd1)
summary(fit)
```








```{r}
ggplot(data = kki.adhd, aes(x = mABC_AGE,y = mABC_TotalStandardScore)) + geom_point() + geom_smooth()
```


```{r}
ggplot(data = kki.adhd, aes(x = mABC_AGE,y = SRS_TotalRawScore)) + geom_point() + geom_smooth()
```





