---
title: "Thomas WISC Exploration"
author: "Arthur Janes"
date: "11/10/2019"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(gridExtra)
```

Handling the WISC data
```{r, message=FALSE}
kki.demo <- read.csv("KKI_demographicInfo.csv")
kki.social <- read.csv("KKI_SocialResponsivenessScaleQuestionnaire.csv")
kki.movement <- read.csv("KKI_movementAssessmentBatteryforChildren.csv")

wisc <- read.csv("KKI_WechslerIntelligenceScaleforChildren.csv")
wisc4GAI <- read.csv("wisc4GAI_lookup.csv")
wisc5GAI <- read.csv("wisc5GAI_lookup.csv")

wisc4 <- filter(wisc, WISC_VERSION == 4)
wisc5 <- filter(wisc, WISC_VERSION == 5)

wisc4 <- wisc4[-c(11:15)]
wisc5 <- wisc5[-c(5:10)]

wisc4 <- filter(wisc4, visit == 1)
wisc5 <- filter(wisc5, visit == 1)

#Calculate composite scores for both WISC versions
wisc4$score <- rowSums(wisc4[,5:10])
wisc5$score <- rowSums(wisc5[,5:9])

#Filter out NA scores
wisc4 <- na.omit(wisc4, cols = "score")
wisc5 <- na.omit(wisc5, cols = "score")

#Convert composite scores to GAI scores for WISC version 4
composite4 = rep(0,length(wisc4[,1]))
for (i in 1:length(wisc4[,1])) {
  composite4[i] <- wisc4GAI[wisc4[i,11]-5,2]
}
wisc4$GAI <- composite4

#Convert composite scores to GAI scores for WISC version 5
composite5 = rep(0,length(wisc5[,1]))
for (i in 1:length(wisc5[,1])) {
  composite5[i] <- wisc5GAI[wisc5[i,10]-4,2]
}
wisc5$GAI <- composite5

#Remove composite scores
wisc4 <- wisc4[-c(2:11)]
wisc5 <- wisc5[-c(2:10)]

#Combine WISC data
wisc.combo <- full_join(wisc4, wisc5, by = c('ID', 'GAI'))
```

Reading in the KKI data
```{r, message=FALSE, warning=FALSE}
#Fix odd ID col
colnames(kki.demo)[1] <- "ID"
colnames(kki.social)[1] <- "ID"
colnames(kki.movement)[1] <- "ID"
kki <- merge(kki.demo,kki.social)
kki <- merge(kki,kki.movement)
#Now have all the data in a huge data frame

#Removing N/A values. Mostly removing second visits.
kki <- na.omit(kki)

#Combine kki with WISC version 4 data
kki.wisc <- full_join(kki, wisc.combo, by = 'ID')

#Make new data frames multiple diagnoses, single diagnosis, no diagnosis
kki2 <- filter(kki.wisc, PrimaryDiagnosis != "None",SecondaryDiagnosis ==c("Yes", "No"))
multdia <- filter(kki.wisc, PrimaryDiagnosis != "None", SecondaryDiagnosis =="Yes")
singdia <- filter(kki.wisc, PrimaryDiagnosis != "None" , SecondaryDiagnosis == "No")
nodia <- filter(kki.wisc, PrimaryDiagnosis =="None" , SecondaryDiagnosis =="No")
```

Hand Data
```{r}
kki.hand <-  read.csv("KKI_handedness.csv")
colnames(kki.hand)[1] <- "ID"
kki.hand <- filter(kki.hand, visit == 1)
kki.hand <- kki.hand[-c(2)]
kki.wisc <- full_join(kki.wisc, kki.hand, by = 'ID')
```

WISC Score by Primary Diagnosis
```{r}
ggplot(data = kki.wisc, aes(x = PrimaryDiagnosis, y = GAI)) + geom_boxplot()
```

WISC Score vs. SRS Score
```{r message=FALSE, warning=FALSE}
ggplot(data = kki.wisc, aes(x = GAI, y = SRS_TotalRawScore)) + geom_point() + ggtitle("SRS Score vs. WISC Score") + labs(x = "WISC Score", y = "SRS Score") + geom_smooth() + geom_smooth(method = 'lm', colour = 'red')

ggplot(data = kki.wisc, aes(x = GAI, y = SRS_TotalRawScore, colour = PrimaryDiagnosis)) + geom_point() + ggtitle("SRS Score vs. WISC Score Colored by Primary Diagnosis") + labs(x = "WISC Score", y = "SRS Score") + geom_smooth()
```

WISC Score vs. mABC Score
```{r message=FALSE, warning=FALSE}
ggplot(data = kki.wisc, aes(x = GAI, y = mABC_TotalStandardScore)) + geom_point() + ggtitle("mABC Score vs. WISC Score") + labs(x = "WISC Score", y = "mABC Score") + geom_smooth() + geom_smooth(method = 'lm', colour = 'red')

ggplot(data = kki.wisc, aes(x = GAI, y = mABC_TotalStandardScore, colour = PrimaryDiagnosis)) + geom_point() + ggtitle("mABC Score vs. WISC Score Colored by Primary Diagnosis") + labs(x = "WISC Score", y = "mABC Score") + geom_smooth()
```

Wisc Score vs. Balance
```{r message=FALSE, warning=FALSE}
ggplot(data = kki.wisc, aes(x = GAI, y = mABC_Balance.Component.StandardScore)) + geom_point() + ggtitle("mABC Balance vs. WISC Score") + labs(x = "WISC Score", y = "mABC Balance") + geom_smooth() + geom_smooth(method = 'lm', colour = 'red')

ggplot(data = kki.wisc, aes(x = GAI, y = mABC_Balance.Component.StandardScore, colour = PrimaryDiagnosis)) + geom_point() + ggtitle("mABC Balance vs. WISC Score Colored by Primary Diagnosis") + labs(x = "WISC Score", y = "mABC Balance") + geom_smooth()
```

```{r message=FALSE, warning=FALSE}
ggplot(data = kki.wisc, aes(x = GAI, y = mABC_ManualDexterity.Component.StandardScore)) + geom_point() + ggtitle("mABC Dexterity vs. WISC Score") + labs(x = "WISC Score", y = "mABC Dexterit") + geom_smooth() + geom_smooth(method = 'lm', colour = 'red')

ggplot(data = kki.wisc, aes(x = GAI, y = mABC_ManualDexterity.Component.StandardScore, colour = PrimaryDiagnosis)) + geom_point() + ggtitle("mABC Dexterity vs. WISC Score Colored by Primary Diagnosis") + labs(x = "WISC Score", y = "mABC Dexterity") + geom_smooth()
```

```{r message=FALSE, warning=FALSE}
ggplot(data = kki.wisc, aes(x = GAI, y = mABC_AimingAndCatching.Component.StandardScore)) + geom_point() + ggtitle("mABC AimingAndCatching vs. WISC Score") + labs(x = "WISC Score", y = "mABC AimingAndCatching") + geom_smooth() + geom_smooth(method = 'lm', colour = 'red')

ggplot(data = kki.wisc, aes(x = GAI, y = mABC_AimingAndCatching.Component.StandardScore, colour = PrimaryDiagnosis)) + geom_point() + ggtitle("mABC AimingAndCatching vs. WISC Score Colored by Primary Diagnosis") + labs(x = "WISC Score", y = "mABC AimingAndCatching") + geom_smooth()
```

```{r}
Move.Age <- ggplot(data = kki.wisc, aes(x = mABC_AGE, y = GAI, colour = PrimaryDiagnosis)) + geom_point(alpha = .3) + geom_jitter() + geom_smooth() + theme(legend.position = 'none')
#low correlation between age and motor skills in all 
# groups
```

```{r}
SRS.Age <- ggplot(data = kki.wisc, aes(x = SRS_AGE, y = GAI, colour = PrimaryDiagnosis)) + geom_point(alpha = .3) + geom_jitter() + geom_smooth() + theme(legend.position = 'none')
#again no real relationship
```

```{r message=FALSE, warning=FALSE}
grid.arrange(Move.Age,SRS.Age, nrow = 1)
```

```{r}
#SRS ~ mABC, .2658
lm1 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore, data = kki.wisc)
#summary(lm1)

#SRS ~ mABC + WISC, .268
lm2 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI, data = kki.wisc)
#summary(lm2)

#SRS ~ mABC + WISC, .2717
lm3 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI + SRS_AGE, data = kki.wisc)
#summary(lm3)

#Multiple Diagnoses: SRS ~ mABC, .05596
lm1 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore, data = multdia)
#summary(lm1)

#Multiple Diagnoses: SRS ~ mABC + WISC, .06019
lm2 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI, data = multdia)
#summary(lm2)

#Single Diagnosis: SRS ~ mABC, .1625
lm1 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore, data = singdia)
#summary(lm1)

#Single Diagnosis: SRS ~ mABC + WISC, .1499
lm2 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI, data = singdia)
#summary(lm2)

#No Diagnosis: SRS ~ mABC, -.001383
lm1 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore, data = nodia)
#summary(lm1)

#No Diagnosis: SRS ~ mABC + WISC, 0.009215
lm2 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI, data = nodia)
#summary(lm2)

#kki2: SRS ~ mABC, 0.1143
lm1 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore, data = kki2)
#summary(lm1)

#kki2: SRS ~ mABC + WISC, .09214
lm2 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI, data = kki2)
#summary(lm2)
```

```{r}
#Autism
aut <- filter(kki.wisc, PrimaryDiagnosis == "Autism")

#No Secondary Diagnosis
no <- filter(aut, SecondaryDiagnosis =="No")
#One Secondary Diagnosis
yes <- filter(aut, SecondaryDiagnosis =="Yes")

#Version 1
uno <- filter(aut, SRS_VERSION == 1)
#Version 2
dos <- filter(aut, SRS_VERSION == 2)

lm <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore, data = aut)
#Adjusted R^2: -.00652
lm2 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI, data = aut)
#Adjusted R^2: -.00746
lm3 <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI + SRS_AGE + Gender, data = aut)
#Adjusted R^2: -.01883

lmNo <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI + SRS_AGE + Gender + SRS_VERSION, data = no)
#Adjusted R^2: .01758
lmYes <- lm(SRS_TotalRawScore ~ mABC_TotalStandardScore + GAI + SRS_AGE + Gender, data = yes)
#Adjusted R^2: -.00241

lmNo <- lm(SRS_TotalRawScore ~ mABC_Balance.Component.StandardScore + GAI + SRS_AGE + Gender, data = no)
#Adjusted R^2: -0.03923
lmYes <- lm(SRS_TotalRawScore ~ mABC_Balance.Component.StandardScore + GAI + SRS_AGE + Gender, data = yes)
#Adjusted R^2: 0.007135

```

